import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.description}>
          <p>フロントのライブラリを簡易的に試すためのプロジェクト</p>
        </div>

        <div className={styles.grid}>
          <Link href={"/giojs"} passHref>
            <div className={styles.card}>
              <>
                <h2>Gio.js &rarr;</h2>
                <p>3Dで地球儀が表示できるライブラリ</p>
              </>
            </div>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href={"/p5js"} passHref>
            <div className={styles.card}>
              <>
                <h2>p5.js &rarr;</h2>
                <p>GenerativeArtっぽいことができるライブラリ</p>
              </>
            </div>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href={"/babylonjs"} passHref>
            <div className={styles.card}>
              <>
                <h2>babylonjs.js &rarr;</h2>
                <p>WebGLのライブラリ</p>
              </>
            </div>
          </Link>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
